[project]
name = "website"
version = "0.1.0"
description = "Custom build tool to generate tailored HTML from markdown posts"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "markdown>=3.7",
    "prettier>=0.0.7",
    "pygments>=2.18.0",
]
